### ISSUE TITLE
[BUG] LOGIN Avatar missing img

### ISSUE THREAD

**Issue by dudlyart** [Redlion-news/issues#27]
**Describe the bug**
Connected with new wallet but default avatar is not kicking in. Well, it shows for moment, and disappears. Missing image placeholder is visible then. Also in profile

**Environnement**
- [X] Production
- [ ] Staging

**To Reproduce**
1. Login with new wallet

**Expected behavior**
Default avatar needs to stay

**Screenshots**
![image](https://user-images.githubusercontent.com/81701877/198116066-83edcbf3-38c0-4b5f-b3e9-21d6f879b756.png)

![image](https://user-images.githubusercontent.com/81701877/198116354-08399a29-fd84-432b-a055-5d4452b8232f.png)

**Comment by qruz-hq** [comment]
Mmmh, I think this isn't happening to fresh wallets, it's happening to old wallets that have data in the db, from the old system. Did you try with a fresh wallet ? @dudlyart

**Comment by dudlyart** [comment]
I tried my other wallet that has some connect history. Its okey for another new wallet. Might be some cache problem. I will set new avatar with holeberlin.eth and it might be gone

**Comment by dudlyart** [comment]
Its ok, we can close this
